# RSNA Knee Abnormality Detection

### Import Libraries

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent.resolve()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

    
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import torch.nn.functional as F

import pydicom

from src.tools import show_dicom_image, show_dicom_info , explore_repository , index_dicom_repository

### Extract data

In [2]:
train_series =  Path("../data/train_series.csv")
train = Path("../data/train.csv")
train_series_dicom = Path("../data/train_series")

In [3]:
study_series_df = pd.read_csv(train_series)
annotation_df = pd.read_csv(train)

### View Data

In [4]:
display(study_series_df.head())

,StudyInstanceUID,SeriesInstanceUID,Fluid_Sensitive,Fat_Suppression,Anatomical_Plane
0,1.2.826.0.1.3680043.8.498.10077803906105306230...,1.2.826.0.1.3680043.8.498.25907331750467633841...,1,1,Sagittal
1,1.2.826.0.1.3680043.8.498.10077803906105306230...,1.2.826.0.1.3680043.8.498.35461930354143940974...,0,0,Sagittal
2,1.2.826.0.1.3680043.8.498.10077803906105306230...,1.2.826.0.1.3680043.8.498.59555639823582486217...,1,1,Axial
3,1.2.826.0.1.3680043.8.498.10077803906105306230...,1.2.826.0.1.3680043.8.498.74334922299557471072...,0,0,Coronal
4,1.2.826.0.1.3680043.8.498.10095687747295410396...,1.2.826.0.1.3680043.8.498.10791858932231443712...,0,0,Sagittal

In [5]:
study_series_df.StudyInstanceUID.nunique() , study_series_df.SeriesInstanceUID.nunique()

(50, 283)

In [6]:
study_series_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 283 entries, 0 to 282
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudyInstanceUID   283 non-null    str
 1   SeriesInstanceUID  283 non-null    str
 2   Fluid_Sensitive    283 non-null    int64
 3   Fat_Suppression    283 non-null    int64
 4   Anatomical_Plane   283 non-null    str
dtypes: int64(2), str(3)
memory usage: 11.2 KB

In [7]:
print(study_series_df.Anatomical_Plane.unique())

<StringArray>
['Sagittal', 'Axial', 'Coronal']
Length: 3, dtype: str

In [8]:
display(annotation_df.head()) , len(annotation_df)

,StudyInstanceUID,Report,ACL,MCL,Medial Meniscus,Lateral Meniscus,Medial OA,Lateral OA,PF OA,Effusion,Synovitis,Baker's,Contusion,Fracture
0,1.2.826.0.1.3680043.8.498.39500553372517290823...,Antecedentes Clínicos:\nArtrosis.\nHallazgos:\...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
1,1.2.826.0.1.3680043.8.498.63519003265636561965...,FINDINGS:\n\nFluid:\nModerate joint effusion. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.2.826.0.1.3680043.8.498.12619895582462244920...,ΜΤ ΑΡΙΣΤΕΡΟΥ ΓΟΝΑΤΟΣ ΤΕΧΝΙΚΗ: Η εξέταση πραγμα...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.2.826.0.1.3680043.8.498.11249981834802444119...,Diz eklemi içi sıvı miktarı hafif derecede art...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.2.826.0.1.3680043.8.498.11382021393803389951...,"In the medial compartment, there is longitudi...",1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

(None, 50)

In [9]:
cols = [
    'StudyInstanceUID', 'SeriesInstanceUID','Anatomical_Plane', 'Report', 'ACL', 'MCL', 'Medial Meniscus',
    'Lateral Meniscus', 'Medial OA', 'Lateral OA', 'PF OA', 'Effusion',
    'Synovitis', "Baker's", 'Contusion', 'Fracture',
    'Fluid_Sensitive', 'Fat_Suppression'
]
merged_df = annotation_df.merge(right=study_series_df , on="StudyInstanceUID" ,how="inner")

merged_df =merged_df[cols]

In [ ]:
merged_df.to_csv("../data/knee_data.csv" , index=False)

In [11]:
train_df = pd.read_csv("../data/knee_data.csv")

In [ ]:

display(train_df.head(10)) , len(train_df)

,Unnamed: 0,StudyInstanceUID,SeriesInstanceUID,Anatomical_Plane,Report,ACL,MCL,Medial Meniscus,Lateral Meniscus,Medial OA,Lateral OA,PF OA,Effusion,Synovitis,Baker's,Contusion,Fracture,Fluid_Sensitive,Fat_Suppression
0,0,1.2.826.0.1.3680043.8.498.39500553372517290823...,1.2.826.0.1.3680043.8.498.10681444947500103079...,Axial,Antecedentes Clínicos:\nArtrosis.\nHallazgos:\...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1,1
1,1,1.2.826.0.1.3680043.8.498.39500553372517290823...,1.2.826.0.1.3680043.8.498.12798253935401276011...,Coronal,Antecedentes Clínicos:\nArtrosis.\nHallazgos:\...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1,1
2,2,1.2.826.0.1.3680043.8.498.39500553372517290823...,1.2.826.0.1.3680043.8.498.33500735563674808256...,Sagittal,Antecedentes Clínicos:\nArtrosis.\nHallazgos:\...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1,1
3,3,1.2.826.0.1.3680043.8.498.39500553372517290823...,1.2.826.0.1.3680043.8.498.48864168281440917690...,Coronal,Antecedentes Clínicos:\nArtrosis.\nHallazgos:\...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0,0
4,4,1.2.826.0.1.3680043.8.498.39500553372517290823...,1.2.826.0.1.3680043.8.498.71452782593498755829...,Sagittal,Antecedentes Clínicos:\nArtrosis.\nHallazgos:\...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0,0

(None, 283)

In [13]:
train_column = train_df.columns
print(len(train_column))

19

In [14]:
with pd.option_context("display.max_colwidth", None):
    display(train_df[["Report"]].head(3))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Report
0  Antecedentes Clínicos:\nArtrosis.\nHallazgos:\nLigamentos cruzados y colaterales dentro de límites normales.\nEl menisco medial es de morfología y señal conservada, sin criterios categóricos de rotura.\nRotura compleja degenerativa del cuerno anterior, cuerpo, cuerno posterior y parte de la raíz\nmeniscal posterior del menisco lateral con extrusión asociada. Edema óseo periférico posterior de\nplatillo tibial lateral con pequeñas fracturas subcorticales regionales.\nÚlceras condrales de espesor parcial y total de la región posterior de carga del compartimento\nfemorotibial lateral. Mínimos cambios óseos asociados. Condropatía superficial del compartimento\nfemorotibial medial y del cartílago troclear.\nÚlceras condrales de espesor parcial y prácticamente total de la faceta lateral de la rótula.\nLeve a moderado derrame articular con mínima sinovitis. No hay quistes poplíteos patológicos.\nTendones cuadricipital, rotuliano, tendones de la pata de ganso, bíceps femoral y banda iliotibial\ndentro de límites normales.\nImpresión:\nRotura compleja degenerativa del cuerno anterior, cuerpo , cuerno posterior y raíz meniscal\nposterior del menisco lateral con extrusión asociada.\nCondropatía lesiones grado 3 y 4 del compartimento femorotibial lateral.\nCondropatía superficial del compartimento femorotibial medial y de la tróclea femoral. Condropatía\nlesiones grado dos y tres de la rótula.\nLeve a moderado derrame articular con mínima sinovitis
1  Antecedentes Clínicos:\nArtrosis.\nHallazgos:\nLigamentos cruzados y colaterales dentro de límites normales.\nEl menisco medial es de morfología y señal conservada, sin criterios categóricos de rotura.\nRotura compleja degenerativa del cuerno anterior, cuerpo, cuerno posterior y parte de la raíz\nmeniscal posterior del menisco lateral con extrusión asociada. Edema óseo periférico posterior de\nplatillo tibial lateral con pequeñas fracturas subcorticales regionales.\nÚlceras condrales de espesor parcial y total de la región posterior de carga del compartimento\nfemorotibial lateral. Mínimos cambios óseos asociados. Condropatía superficial del compartimento\nfemorotibial medial y del cartílago troclear.\nÚlceras condrales de espesor parcial y prácticamente total de la faceta lateral de la rótula.\nLeve a moderado derrame articular con mínima sinovitis. No hay quistes poplíteos patológicos.\nTendones cuadricipital, rotuliano, tendones de la pata de ganso, bíceps femoral y banda iliotibial\ndentro de límites normales.\nImpresión:\nRotura compleja degenerativa del cuerno anterior, cuerpo , cuerno posterior y raíz meniscal\nposterior del menisco lateral con extrusión asociada.\nCondropatía lesiones grado 3 y 4 del compartimento femorotibial lateral.\nCondropatía superficial del compartimento femorotibial medial y de la tróclea femoral. Condropatía\nlesiones grado dos y tres de la rótula.\nLeve a moderado derrame articular con mínima sinovitis
2  Antecedentes Clínicos:\nArtrosis.\nHallazgos:\nLigamentos cruzados y colaterales dentro de límites normales.\nEl menisco medial es de morfología y señal conservada, sin criterios categóricos de rotura.\nRotura compleja degenerativa del cuerno anterior, cuerpo, cuerno posterior y parte de la raíz\nmeniscal posterior del menisco lateral con extrusión asociada. Edema óseo periférico posterior de\nplatillo tibial lateral con pequeñas fracturas subcorticales regionales.\nÚlceras condrales de espesor parcial y total de la región posterior de carga del compartimento\nfemorotibial lateral. Mínimos cambios óseos asociados. Condropatía superficial del compartimento\nfemorotibial medial y del cartílago troclear.\nÚlceras condrales de espesor parcial y prácticamente total de la faceta lateral de la rótula.\nLeve a moderado derrame articular con mínima sinovitis. No hay quistes poplíteos patológicos.\nTendones cuadricipital, rotuliano, tendones de la pata de ganso, bíceps femoral y banda iliotibial\ndentro de límites normales.\nImpresión:\nRotura compleja degenerativa del cuerno anterior, cuerpo , cuerno posterior y raíz meniscal\nposterior del menisco lateral con extrusión asociada.\nCondropatía lesiones grado 3 y 4 del compartimento femorotibial lateral.\nCondropatía superficial del compartimento femorotibial medial y de la tróclea femoral. Condropatía\nlesiones grado dos y tres de la rótula.\nLeve a moderado derrame articular con mínima sinovitis

In [15]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 283 entries, 0 to 282
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         283 non-null    int64
 1   StudyInstanceUID   283 non-null    str
 2   SeriesInstanceUID  283 non-null    str
 3   Anatomical_Plane   283 non-null    str
 4   Report             283 non-null    str
 5   ACL                124 non-null    float64
 6   MCL                124 non-null    float64
 7   Medial Meniscus    124 non-null    float64
 8   Lateral Meniscus   124 non-null    float64
 9   Medial OA          124 non-null    float64
 10  Lateral OA         124 non-null    float64
 11  PF OA              124 non-null    float64
 12  Effusion           124 non-null    float64
 13  Synovitis          124 non-null    float64
 14  Baker's            124 non-null    float64
 15  Contusion          124 non-null    float64
 16  Fracture           124 non-null    float64
 17  Fluid_Sensitive    283 non-null    int64
 18  Fat_Suppression    283 non-null    int64
dtypes: float64(12), int64(3), str(4)
memory usage: 42.1 KB

In [17]:
from dotenv import load_dotenv
import os

load_dotenv()

models = os.getenv("LLMS_AVAILABLE", "")
print(models.split(",") if models else [])

['anthropic/claude-sonnet-5@default', 'deepseek-ai/deepseek-r1-0528', 'google/gemini-3-flash-preview', 'google/gemini-3.1-flash-lite-preview', 'ibm/granite-4.0-h-small', 'openai/gpt-5.4-nano-2026-03-17', 'openai/gpt-oss-120b', 'qwen/qwen3-next-80b-a3b-instruct']